Fichier de configuration php.ini pour PHP

;;;;;;;;;;;;;;;;;;;;;
; Paramètres de base ;
;;;;;;;;;;;;;;;;;;;;;

; Définit la version PHP à utiliser
engine = On

; Permet l'affichage des erreurs (utile en développement)
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; Répertoire des fichiers de sessions
session.save_path = "/tmp"

;;;;;;;;;;;;;;;;;;
; Extensions PHP ;
;;;;;;;;;;;;;;;;;;

; Active l'extension MySQLi (pour les bases de données MySQL)
extension=mysqli.so

; Active l'extension cURL
extension=curl.so

; Active l'extension GD (pour la manipulation d'images)
extension=gd.so

; Active l'extension mbstring (pour les encodages multibytes)
extension=mbstring.so

;;;;;;;;;;;;;;;;;;
; Paramètres d'upload ;
;;;;;;;;;;;;;;;;;;

; Limite la taille maximale d'un fichier uploadé via PHP (en octets)
upload_max_filesize = 2M

; Limite la taille des données POST
post_max_size = 8M

;;;;;;;;;;;;;;;;;;;
; Paramètres de sécurité ;
;;;;;;;;;;;;;;;;;;;

; Désactive l'exécution de fonctions dangereuses (par exemple, system(), exec(), etc.)
disable_functions = system, exec, passthru, shell_exec, proc_open, popen

; Répertoire où les fichiers temporaires de PHP sont stockés
sys_temp_dir = "/tmp"

;;;;;;;;;;;;;;;;;;;
; Paramètres de la mémoire ;
;;;;;;;;;;;;;;;;;;;

; Limite la quantité de mémoire que peut consommer un script
memory_limit = 128M

;;;;;;;;;;;;;;;;;;;;;
; Paramètres de time zone ;
;;;;;;;;;;;;;;;;;;;;;

; Spécifie le fuseau horaire à utiliser
date.timezone = "Europe/Paris"

clear_env = no
listen = wordpress:9000